### PR TITLE
fix: remove unused/outdated image fragments

### PR DESCRIPTION
**Pull request by rexxars**
We used to copy a "fragments" file that Gatsby automatically would discover, in line with what other source plugins did.
This is no longer necessary, and the fragments reference undefined types. With this PR, we remove them altogether.

Prettier had some fun with the README, sorry for the noise.

### CODE REVIEW

**Review by bjoerge — APPROVED** [review]
LGTM!

**Comment by ivoiv** [comment]
Is this getting merged anytime soon?

**Comment by philschonholzer** [comment]
Can someone merge this please? This fixes problems with generating types: #114

**Comment by rexxars** [comment]
Released in [v7.0.5](https://github.com/sanity-io/gatsby-source-sanity/releases/tag/v7.0.5), thanks for your patience

**Pull request merged**
