### PR TITLE
fix: don't add gatsby internals to resolved reference gatsby nodes

### PR DESCRIPTION
**Pull request by AdamDemirel**
This PR resolves issues which occurs for Incremental Builds in Gatsby, when using the plugin.

The way that the Incremental Builds feature works is that it marks routes (HTML files + JSON page data) for regeneration if any of the following inputs change: https://www.gatsbyjs.com/docs/debugging-incremental-builds/#how-does-it-work

Our team experienced an issue where files were getting marked for regeneration on every build, even with no frontend code changing, or updates in the CMS.

The result of diffing between builds showed that the `page-data/*.json` files being outputted by the gatsby build had a changing value for the `counter` property in the `internal` object, sourced by the `gatsby-source-sanity` plugin: 
image

This is a bug, since the counter result is changed between builds and these internals don't need to be exposed for node creation - they are used by Gatsby internally for tracking performance, and tests etc.

This small commit simply filters out those internals from getting added to the node to prevent the `counter` value changing to cause the pages to be marked for rebuild.
 
[Here's](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAJwKYFsCGAHASpgdwDEZUAbAEwGcAKOAIwCsAuRAb0QG0BrVAT1ZUoyGGADmAXVaYwfRAF8AlOwBQiRBARDEomLExlWHHv0HDRk6bIWIAvO3lqUqKCGRIA8k1TQAdLz5aBkZFXzQKEAhUGhpMCAgAGkQA5VsAPlV1dRhgRBoAu1t7ACJRKFR3A2LlNFd3RDiIAG4nbNz8-l8hTGQoKgB1PQALGmKAfWRCABFMKExq5TZWrLIXRDnkMRcAaX47ZM6qMhgomgAORRVl9QB6G8QAGTg4bkRgOGREAFVsbAqAYUwVFQiAAbj0YDIoG8YMghEkcogwHBoe9wBQksI5BBMOhyIDgdd1j0tlBdnJ7FA+H84LlgpwNqTyRJCiV0ahgKJUBRiogAPzEzY7ficAAMEl8UDgTwIAKB0WUAGpBUzDsdTgBGZSsRnCvhXLJZRoMkl6ln2ekBCTLeSIcjAnTtACExqtiyJrv45sQlq9NuWtTcSEaTnkCLAekhZEujhUq2hyIoIPsS3UYxgFFYAHJsJgtgBJMDdMSTdBZhJOMZUv7Z3MFotzEu48uVtCg7MAKW4AFECABZAgAdjgAEEAIoAISmD3+AC18wBWdC4BcwDsttMQNCzbkjqDZgBMooPGoAtKKzueACwAFVFV+YooXzAAzKLZxvEGMQNgKDuKHuh7HmeF6ngeACcN4HgezAai+sGDh+FbqJoYDlGhrCcMsqaGl+ATZsAg7xFeg5PqgqAAGwLsAmALgeqAnleqCDuBHKoJg9BnAeV4ap+hpVtSqDZvQZBwBA3B8VkEBDDAlBoGAmEjsgkx8BIyG4VgyDcFMHJUIpymYKp6mGkIfCrNmyLIFgZBZjaxmZLhYz4YgWZwRAFD0BAg6oBqEAasAklptWQkuSJYkSfZKEyXJqAKVwSkqWpRKadpumYUluGIKZ5kuZZ1m2YajjqBl6x6DlWYAMpDHA2CIIWxalp+biGC5NyiA1zbqRM0yzJg-wIOh+5cNhRJOaYLmEcRpELuRVE0XRDEakxLFsRxXE8YFX7BcJoniZt0myRQ8n6YlkWIClOnAHp8UGUZRLZSFWZ5QYBVZGGI2ZWNAguW5HleT5fkBWdAk1qFu0RUSB0xXFnAJYZJWGhdaVcAjWQPRZHz5f6xVdZMBAzHMfYuJgf5zKw7KcmA3LqRm2anpgHEUAewCiuBp7cguL6nguC5JqerH0BRp4s1eopPmcosLhqFCflDR2xelNNoRUYAGEYyzbS5FUyHofAAAp5qg9WNo19moYNUwwFsQjZleL4vhRFCEbRg4URqZwUURV4LvQ4FnOB4ELq7GoLhRFHABAklwAQVPINmYizFQ9B8KeVBwG4USpzrVKSZo4DlHHiB2y+obqbm8lDWAIBkGQKixioqFp6sviiWINBoFgeCECQ5DUDQiaoIoihAA) a TS REPL demoing that the property gets dropped as expected with the change introduced in this commit

### CODE REVIEW

**Comment by dotdev-support** [comment]
Bump to get some attention on this...

**Comment by evenwestvang** [comment]
Thank you for submitting and bumping. We'll have a look.

**Review by stipsan — APPROVED** [review]

**Comment by stipsan** [comment]
Great fix @dotdev-support! Merging and releasing in a few minutes 😄

**Comment by stipsan** [comment]
Gonna merge, will fix failing tests post merge 👍

**Comment by stipsan** [comment]
Released under [v7.4.1](https://github.com/sanity-io/gatsby-source-sanity/releases/tag/v7.4.1) 🎉

**Pull request merged**
